[project]
name = "example-playwright-pytest-testbeats"
version = "0.1.0"
description = "Example Playwright Pytest TestBeats"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "playwright>=1.52.0",
    "pytest-playwright>=0.7.0",
]
